### ISSUE TITLE
publish-nuget doesn't work

### ISSUE THREAD

**Issue by cuzzlor** [rohith/publish-nuget#1]
Hi Rohith,

I tried to follow setting this action up via the marketplace.

I get this error:

```
Download action repository 'rohith/publish-nuget@v1'
##[warning]Failed to download action 'https://api.github.com/repos/rohith/publish-nuget/tarball/v1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 26.063 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/rohith/publish-nuget/tarball/v1'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 17.956 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).
```

**Comment by rohith** [comment]
@cuzzlor Thanks for reporting this 🤝

I was wrong to assume that github takes care of fetching a latest version based on the semantic major but it's fixed now you can just re-run the action

**Comment by cuzzlor** [comment]
Thank you @rohith that works nicely for me now, much appreciated!

https://github.com/cuzzlor/password-check/blob/master/.github/workflows/build-test-publish.yml
