### ISSUE TITLE
NUGET_KEY not given

### ISSUE THREAD

**Issue by alexandresanlim** [rohith/publish-nuget#14]
I have set my secrets NUGET_KEY in my project but return me a message "NUGET_KEY not given"

### **My project info**

**Secrets settings page:**
![image](https://user-images.githubusercontent.com/5353685/76019947-542c0b00-5f01-11ea-9239-01b5ffd49329.png)

**My publish config:**
https://github.com/infinitussolutions/InfinitusApp.Client.Net/blob/master/.github/workflows/publish.yml

**Comment by sven-n** [comment]
You probably need to remove the '# ' in front of the setting (line 29).
