### ISSUE TITLE
HTTP 409 when publishing multiple projects

### ISSUE THREAD

**Issue by sven-n** [rohith/publish-nuget#15]
Thank you for this great action!
I'm currently trying to set it up for one of my projects. Similar to #9, I want to publish multiple projects in one job. In my case, the projects build to the same output directory.
So, when the second package is about to be pushed, the first one is sent again, because of the specified ```*.nupkg``` filename pattern.
```javaScript
const NUGET_PUSH_RESPONSE = this._execAndCapture(`dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${this.NUGET_KEY}`)
```

This leads to an http result 409 and lets the Action fail. My error message is this one:
```
##[error]😭 error: Response status code does not indicate success: 409 (A package with ID '...' and version '...' already exists and cannot be modified.).
```

Suggestions:
  * Extend the filename pattern to ```${this.PACKAGE_NAME}*.nupkg```. In this case, the user still has to take care if he wants to publish for example "A.B" and "A". The "A" needs to published first, then "A.B".
  * Add the parameter ```--skip-duplicate```, so the error 409 isn't returned.

Thank you :)

**Comment by rohith** [comment]
Thank you 🙌 for taking your time out to write such a detailed description with fix suggestions too

I went with `${this.PACKAGE_NAME}*.nupkg` as the `--skip-duplicate` is dependent on .net core sdk version

Please feel free to raise a PR when you know how to fix an issue. Issue / PR either way you contributed to this actions so 🤝
