### ISSUE TITLE
Also a question regarding multiple projects

### ISSUE THREAD

**Issue by LegendaryB** [rohith/publish-nuget#16]
Hey,

thank you for this action! I also have a question regarding multiple projects. I'm new to Github Actions so sorry.

I have the following structure:
Root Folder -> src\Project1
Root Folder -> src\Project2

and so on. How do I get this action to publish everything under src? It is somehow possible? 

Kind Regards,
Daniel

**Comment by LegendaryB** [comment]
Okay figured it out. But now I have the problem that it doesn't find my packages.
Test Repo: https://github.com/LegendaryB/GitHubNuGetAutomaticPushTest
Workflow: https://github.com/LegendaryB/GitHubNuGetAutomaticPushTest/edit/master/.github/workflows/publish-nuget.yml

**Comment by LegendaryB** [comment]
Figured it out

**Comment by AraHaan** [comment]
@LegendaryB how did you make it work, can it work with wildcard projects so I can move everything on each of my repositories with an ``.github`` folder to a repository named ``.github`` to actually store them in there (including dependabot config there too if possible)?
