### ISSUE TITLE
F# Support

### ISSUE THREAD

**Issue by sanchez** [rohith/publish-nuget#5]
I would love to be able to publish my F# projects using this library! (Currently it can't find the project)

**Comment by rohith** [comment]
Sure, I'll get it done 👍

**Comment by sanchez** [comment]
You are a legend, however F# using PackageVersion instead of Version (so your version regex is out of date), I have also noticed if I do a series of commits and then push it will sometimes fail to detect the change and upload (I believe this is due to the use of the diff to get the version difference)

**Comment by rohith** [comment]
> You are a legend, however F# using PackageVersion instead of Version (so your version regex is out of date)

The regex looks at `Version` as it's the most commonly used one, do you actually intend for a `Version` & `PackageVersion` divergence? 😕

> I have also noticed if I do a series of commits and then push it will sometimes fail to detect the change and upload (I believe this is due to the use of the diff to get the version difference)

Got it, a fix is on the way 🔧
